# Generated by Django 4.2.13 on 2024-07-10 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='9196', max_length=4),
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=30, unique=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_category', models.CharField(choices=[('Customer', 'Customer'), ('Lead', 'Lead')], max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('industrial_sector', models.CharField(choices=[('Engineering', 'Engineering')], max_length=50)),
                ('account_rating', models.IntegerField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=11, null=True)),
                ('office_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('billing_address', models.CharField(max_length=255)),
                ('billing_state', models.CharField(max_length=100)),
                ('shipping_address', models.CharField(max_length=200)),
                ('shipping_state', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.lead')),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounttype')),
                ('billing_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shipping_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shipping_city', to='accounts.city')),
            ],
        ),
    ]
