# Generated by Django 4.2.13 on 2024-07-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_city_alter_otptoken_otp_code_customeraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='shipping_post_code',
            field=models.CharField(default='10234', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='5655', max_length=4),
        ),
    ]
