# Generated by Django 4.2.13 on 2024-07-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customeraccount_billing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='5640', max_length=4),
        ),
    ]
