# Generated by Django 4.2.13 on 2024-07-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_opportunity_close_date_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='Opportunity_slug',
            field=models.SlugField(default='computer-village-project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='2065', max_length=4),
        ),
    ]
