# Generated by Django 4.2.13 on 2024-07-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_otptoken_otp_code_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_slug', models.SlugField(blank=True, null=True)),
                ('industry_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='2557', max_length=4),
        ),
    ]
