# Generated by Django 4.2.13 on 2024-07-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_industry_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry_name',
            field=models.CharField(default='Agriculture', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='0557', max_length=4),
        ),
    ]
