# Generated by Django 4.2.13 on 2024-07-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_department_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='departments',
            field=models.ManyToManyField(to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='6862', max_length=4),
        ),
    ]
